name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout moon
        uses: actions/checkout@v4

      - name: Install Dependencies and Build
        run: |
          npm install  # Adjust for your build process
          npm run build

      - name: Clone GH pages via HTTPS
        run: |
          git clone https://github.com/michaelschung/michaelschung.github.io.git --depth=1
          rm -rf michaelschung.github.io/OTHER/moon  # Remove old deployment (optional)
          mv dist michaelschung.github.io/OTHER/moon

      - name: Commit and Push to GH pages
        run: |
          cd michaelschung.github.io
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy updated moon to GH pages" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAGES_PAT }}@github.com/michaelschung/michaelschung.github.io.git main
